# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IvyGate
email: tips@ivygateblog.com
description: > # this means to ignore newlines until "baseurl:"
  IvyGate, the Ivy League blog, covers news, gossip, sex, sports and more at Brown,
  Columbia, Cornell, Dartmouth, Harvard, Penn, Princeton and Yale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ivygateblog.com" # the base hostname & protocol for your site
twitter_username: ivygate
github_username:  ivygateblog

# Build settings
markdown: kramdown
